/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bigdata' at '5/21/19 3:01 PM' with Gradle 2.14.1
 *
 * @author Bigdata, @date 5/21/19 3:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
